### ISSUE TITLE
Year is missing when using DateTime.fromObject({birthDate}).toISODate()

### ISSUE THREAD

**Issue by detoner777** [moment/luxon#1328] opened 2022-11-17 15:10 UTC
**Description**
Weird bug, I use luxon with Next.js, and on my local machine it works great:

`const date =  DateTime.fromObject({year: 1999, month: 09, day: 09}).toISODate()`
it returns `date === '1999-09-09'`;

But after deployed to Vercel, the code above does not parse the year,
 it returns  `date === '-09-09'`;
 
 and I use the same machine and the same browser just a different tab.
 

- macOS: 13.0
- Browser: Chrome Version 107.0.5304.87 (Official Build) (x86_64)
- Luxon version: "2.5.0"
- Your timezone [e.g. "America/New_York"]
- Next.js: "13.0.3"

The same happens in Firefox Browser and on other machines.

**Comment by icambron** [comment] 2022-11-17 18:36
Hard to tell if you're running into an issue parsing the date or in `toISODate`...

Can you provide the output of `DateTime.fromObject({year: 1999, month: 09, day: 09}).toObject()` and also just print out `DateTime.fromObject({year: 1999, month: 09, day: 09})`

**Comment by davecarlson** [comment] 2022-11-19 17:16
I can confirm i'm having the same issue on vercel on a new deployment. Luxon 3.1.0

works fine locally.

**Comment by zachgoll** [comment] 2022-11-22 15:27
By the looks of it, [this commit](https://github.com/vercel/next.js/commit/3d62f467cf4644e3e087f8db954d0db7156c69ea) should fix the issue on the Next.js side of things, still waiting for a release on that.  In the meantime, setting `swcMinify: false` in `next.config` seems to fix.

**Comment by patdx** [comment] 2022-11-29 04:05
I had run into a similar issue with some code like `DateTime.fromSQL(raw.ts, { zone: "Asia/Hong_Kong" }).toUTC().toISO();
` After upgrading Next.js from 13.0.4 to 13.0.5 it went away.

**Comment by icambron** [comment] 2022-11-29 04:27
A minification issue makes sense to me. @zachgoll do you know what the root SWC issue and fix was?

At any rate, since this is fixed in the latest Next, closing this one out.

**Closed by icambron** 2022-11-29 04:27 UTC
Labels: issue: troubleshooting
