### ISSUE TITLE
DateTime.toFormat('ZZZZ') not showing expected output

### ISSUE THREAD

**Issue by eragon512** [moment/luxon#499] opened 2019-05-07 11:08 UTC
According to the [docs](https://moment.github.io/luxon/docs/manual/formatting.html#table-of-tokens), when the 'ZZZZ' token is passed in the format string, the abbreviated named offset string should be displayed in the output string. 
However, the timezone offset from GMT is being displayed instead.

Code snippet to test the issue:
```js
DateTime.fromISO("2019-05-03T10:59:22Z")
.setZone("America/Los_Angeles")
.toFormat('dd-MMM-yy hh:mm:ss ZZZZ');
```

Expected Output:
```
03-May-19 03:59:22 PDT
```

Actual Output:
```
03-May-19 03:59:22 GMT-7
```

Package Version: `^1.13.0`

Environments: `node@12.1.0`, `Chrome`

**Comment by icambron** [comment] 2019-05-07 20:27
I'm not able to reproduce this in Chrome or Node 10.15.1 (I get "PDT" for both). I also can't really imagine how this would happen. Are you sure that code breaks for you when run in isolation?

**Comment by icambron** [comment] 2019-05-08 15:02
I guess I was thrown off by you saying it reproduces in Chrome. I'll try Node 12

**Comment by icambron** [comment] 2019-05-09 06:27
I upgraded my Mac to Node 12.1.0 and I still get PDT. I think you must have something else going on. Can you confirm that in a totally fresh Node repl session, if you import Luxon and run just that code snippet, that you get "GMT-7"? Is there anything else strange about your environment? What operating system?

**Comment by eragon512** [comment] 2019-05-09 19:41
Okay, this issue only occurs when I use a [`fish`](https://fishshell.com/docs/current/tutorial.html) terminal and use a node REPL inside it 

It works as expected on node@12.2.0 on a normal terminal

I'm using a Mac (High Sierra v10.13.6)

**Comment by icambron** [comment] 2019-05-09 20:34
Odd. Can you run this in that repl and tell me what you get back?

```js
new Intl.DateTimeFormat("en", { timeZoneName: "short", timeZone:"America/Los_Angeles" }).format(new Date())
```

**Comment by eragon512** [comment] 2019-05-10 18:10
I get this in the output: 
```
5/10/2019, PDT
```

**Comment by icambron** [comment] 2019-05-10 21:18
Thanks. Well, I'm perplexed. I'd pretty much have to install fish and debug it. I'll get to that but it'll probably be a bit

**Comment by mdanka** [comment] 2019-05-28 10:43
I see a similar (the same?) issue.

Reproduced here: https://jsfiddle.net/27mjao40/

![Screenshot 2019-05-28 at 12 42 03](https://user-images.githubusercontent.com/8069999/58472194-05696d80-8146-11e9-90ba-c0ce06444325.png)

* Chrome Version 74.0.3729.169 (Official Build) (64-bit)
* MacOS Mojave Version 10.14.5

Is there anything I can help to debug it?

**Comment by icambron** [comment] 2019-05-29 04:06
@mdanka I think that's different. What you're seeing is just this:

```js
new Intl.DateTimeFormat("en", { timeZoneName: "short", timeZone: "America/Los_Angeles" }).format()
"5/28/2019, PDT"

new Intl.DateTimeFormat("en-gb", { timeZoneName: "short", timeZone: "America/Los_Angeles" }).format()
"28/05/2019, GMT-7"
```

So Luxon picks that up and thinks the British word for "PDT" is "GMT-7". That's a bit weird on Chrome's part, but no mystery, really.

I had originally thought this was the OP's problem too, and that his shell just had a different locale set on it, but Luxon specifically ignores the system locale in `toFormat()`, so unless that logic is broken, the OP's issue is still at large...

**Comment by mdanka** [comment] 2019-05-29 10:30
@icambron Thanks for catching that, you're right.

So in Chrome, `CEST` is OK in `en-gb` but becomes `GMT+2` in `en-us`, and `PDT` is OK in `en-us`, but becomes `GMT-7` in `en-gb`.

In `moment` I seem to get all the abbreviations for both `en-us` and `en-gb`. Do you think there's a way (some meta-locale) to get this in luxon, or given luxon's architecture you'd say that this is an issue with Chrome?

**Comment by icambron** [comment] 2019-05-29 14:40
First part: yes, Luxon doesn't have locale data of its own. It just has what Chrome has, so locale data bugs are Chrome data bugs.

Second part: yeah, that's interesting and is similar to the OP's problem. I'll take a closer look

**Comment by icambron** [comment] 2019-06-01 22:42
Yup, a bug. There's some logic for making this happen:

> Defaults to en-US if no locale has been specified, regardless of the system's locale

but the zone tokens in particular were ignoring it.

I think this is probably the OP's issue too; that one shell has an env var setting the locale to en-gb, which triggered it.

Fixed in 6c7d84d3e5f08b7115a3a1ab31cdf093bc3fbf5e, released in 1.16.0

**Closed by icambron** 2019-06-01 22:42 UTC
Labels: issue: troubleshooting

**Comment by vvo** [comment] 2020-09-29 08:41
Hey there, I have been struggling on a very similar issue:

I am testing this in the latest Chrome (85), result is the same in Node v14.12.0:

new Intl.DateTimeFormat("en-US", { timeZoneName: "short", timeZone:"America/Los_Angeles" }).format(new Date())
"9/29/2020, PDT"

new Intl.DateTimeFormat("en-US", { timeZoneName: "short", timeZone:"Europe/Paris" }).format(new Date())
"9/29/2020, GMT+2"

Any idea why Europe/Paris would not give me the abbreviated "CEST"?

Note that en-GB works:

new Intl.DateTimeFormat("en-GB", { timeZoneName: "short", timeZone:"Europe/Paris" }).format(new Date())
"29/09/2020, CEST"

My system settings:
![image](https://user-images.githubusercontent.com/123822/94534024-3842da80-0240-11eb-9d59-bb2b60fac7eb.png)

MacOS 10.15.6

I haven't been able to find the exact reason why this is not working as expected, is there some missing internationalization data?

**Comment by gdebunne** [comment] 2020-09-29 13:55
I have the same results using Firefox 81.0 on the same OS.
For a non-DST date (i.e. in the winter), it returns `GMT+1` or `CET` respectively.

**Comment by Adamfsk** [comment] 2021-06-21 13:07
I'm getting the same issue on MacOS Big Sur while running tests in Jest on Node 16.3.

`ZZZZ` returns `GMT+2` (expected `CEST`)
`ZZZZZ` returns `Central European Summer Time`
