### ISSUE TITLE
I have some doubts about the fixOffset function

### ISSUE THREAD

**Issue by LiuTing0403** [moment/luxon#1656] opened 2024-09-23 09:16 UTC
```
// find the right offset a given local time. The o input is our guess, which determines which
// offset we'll pick in ambiguous cases (e.g. there are two 3 AMs b/c Fallback DST)
function fixOffset(localTS, o, tz) {
  // Our UTC time is just a guess because our offset is just a guess
  let utcGuess = localTS - o * 60 * 1000;


  // Test whether the zone matches the offset for this ts
  const o2 = tz.offset(utcGuess);


  // If so, offset didn't change and we're done
  if (o === o2) {
    return [utcGuess, o];
  }


  // If not, change the ts by the difference in the offset
  utcGuess -= (o2 - o) * 60 * 1000;


  // If that gives us the local time we want, we're done
  const o3 = tz.offset(utcGuess);
  if (o2 === o3) {
    return [utcGuess, o2];
  }


  // If it's different, we're in a hole time. The offset has changed, but the we don't adjust the time
  return [localTS - Math.min(o2, o3) * 60 * 1000, Math.max(o2, o3)];
}
```

` return [localTS - Math.min(o2, o3) * 60 * 1000, Math.max(o2, o3)];` I don't understand this line. Why do we use Math.min(o2, o3) when calculate utcGuess, but use Math.max(o2, o3) when calculate utcOffset?

**Comment by esetnik** [comment] 2024-09-26 17:12
I am also wondering if there is some bug here that is affecting `.plus()` in a negative way. I have a recurring issue where somehow the end date of the interval is getting a different (incorrect) timezone applied https://github.com/moment/luxon/issues/909#issuecomment-2339117223.

**Comment by diesieben07** [comment] 2024-09-26 20:06
Let me explain what this function does, in terms of an example.
Let's say you're asking to create a DateTime for `{ year: 2024, month: 3, day: 31, hour: 1, minute: 30 }` in `Europe/Berlin`.
 
How does Luxon figure out which UTC time a local time belongs to? Firstly, it treats the object you've given it as if it were UTC and turns that into a UTC timestamp. Now we have a UTC timestamp which is the time we are after but _plus_ the offset (this is the `localTS` value in `fixOffset`). We still don't know what the offset actually is. Next, we _guess_ an offset, by asking the time zone "What's the offset _right now_". These two pieces of information (the `localTS` plus the guessed offset) are taken in by `fixOffset` and it's job is to turn these into the correct Unix timestamp (which is in UTC, of course) and the correct offset.

There are three options for the offset:
1. The offset we guessed is correct.
2. The offset we guessed is wrong.
3. The time we're being asked to create, _does not exist_, because it falls into a DST hole (e.g. `2024-03-31T02:30:00` in Europe/Berlin).

## 1. The offset we guessed is correct
This is easy - we just take the offset we guessed and subtract it from the `localTS`. The result is a _guessed_ UTC timestamp. If we ask the time zone "what's the offset at this guessed UTC timestamp" and it matches our offset guess, the guess must be correct, otherwise the math would not work out.

## 2. The offset we guessed is wrong
Like in 1, we're guessing a UTC timestamp from the `localTS` and our guessed offset. But when we ask the time zone "what is the offset at this guessed UTC timestamp" and it tells us something else.
Assuming we guessed an offset of 2 hours, but the correct offset would be 1 hour, then we're _off_ by one hour. So we simply take the difference between our guessed offset and this different offset that the time zone told us about and adjust our current UTC timestamp by that. Effectively what this is doing is shifting our guess from being _in DST_ to being _outside_ DST (or vice versa) by adjusting by the difference in offset between the two.

## 3. The time we've been given _does not exist_
If at the end of 2 we notice "wait, after we've shifted our guess from _in DST_ to _outside DST_ (or vice versa) it _still_ doesn't work out" (because the zone still gives us a different offset) then the only conclusion left must be that the time we've been given is neither in DST nor outside it. Luxon adjusts this invalid time to be _after_ the hole.
Now, if the time we want is after the hole, the correct offset must be the _greater_ of the two offsets, because on a DST transition where the offset becomes _smaller_, there is no hole (because the clock is moved backwards - you instead have duplicate local times). As such this DST transition we're in right now must be from a smaller to a larger offset - and we want the larger one, because we want a time that is _later_ (after the hole). **That is why the offset is returned as `max(o2, o3)`.**
Now we still need to get the corrected UTC timestamp. We still have `localTS`, which is the UTC timestamp _as if the local time we were given were in UTC_. If we remove the _larger_ offset from this, we get a time instant that is _before_ the DST change. If we remove the _smaller_ offset from this, we get the time instant, that is _after_ the DST change (it's _later_). The latter is what we want, because we're shifting the invalid time _fowards_. 

---

This logic is complicated and very hard to understand (writing this post took me over an hour). But it is correct as far as I can tell.

If you have any further doubts, please point to _**concrete**_ situations where this is wrong, preferably with an example where a wrong result is produced.
Otherwise I'm going to close this issue.

**Comment by esetnik** [comment] 2024-09-26 20:11
I spent a long time tracing the logic of `Interval.after()` to where it utilizes this function `fixOffset`. I cannot explain any other way that the end of the interval would end up having a different timezone than the beginning of the interval when using `Interval.after()`. So I do believe there is some bug in this function.

I have no idea how to reproduce `The end of an interval must be after its start, but you had start=2024-05-01T12:00:00.000-05:00 and end=2024-05-01T12:30:00.000-04:00` but I'm seeing it relatively frequently in our production environment. In all cases there's a +1hr offset between the Interval end date and the interval start date. This shouldn't be possible utilizing `Interval.after()` since it should always have a start and end with the same timezone.

**Comment by diesieben07** [comment] 2024-09-26 20:25
@esetnik In your other issue I already asked you to _please_ provide a way to reproduce this.
You say you don't know how to reproduce this, yet you clearly have some kind of logging system in place. Could you please _add_ to this logging system so that it logs the _exact_ inputs to `Interval.after` _including time zones_ when this error occurs? You are the only person to ever report this issue.
From your example here, it just looks like you passed in wrong values to `Interval.fromDateTimes`. If your example were DST related, there would have to be a DST change _in May_ and _at noon_. Neither happens in any time zone that I am away of.

**Comment by esetnik** [comment] 2024-09-26 20:42
> @esetnik In your other issue I already asked you to _please_ provide a way to reproduce this. You say you don't know how to reproduce this, yet you clearly have some kind of logging system in place. Could you please _add_ to this logging system so that it logs the _exact_ inputs to `Interval.after` _including time zones_ when this error occurs? You are the only person to ever report this issue.

Thanks, I'm not trying to be dismissive or doubtful of your work. This is a fantastic project and I know this is incredibly challenging to get right. We've already added more logging in our production environment to report the requested information, however, we've not received any further instances of this since releasing that logging so I don't have any more details to share at this time.

> From your example here, it just looks like you passed in wrong values to `Interval.fromDateTimes`. If your example were DST related, there would have to be a DST change _in May_ and _at noon_. Neither happens in any time zone that I am aware of.
I agree! However, we are not using `Interval.fromDateTimes()` anywhere in our codebase and we are solely using `Interval.after(startDate, 1800000);`. However, [`Interval.after()` does internally call `Interval.fromDateTimes`](https://github.com/moment/luxon/blob/master/src/interval.js#L113). I just don't understand how the instance passed as `dt.plus(1800000)` has a different offset than `dt`.

**Comment by esetnik** [comment] 2024-09-26 20:47
I also want to add that we've only ever seen the issue related to passing a start DateTime with timezone `America/Chicago` while the user's browser local timezone is `America/New_York` and attempting to add `1800000ms` using `Interval.after()`. The date itself does not seem to correlate with any known DST-related dates.

**Comment by diesieben07** [comment] 2024-09-26 21:28
> I just don't understand how the instance passed as dt.plus(1800000) has a different offset than dt.

The only way this can happen is if there is a DST change or if there is some obscure bug where for some reason your code is the only instance we've seen so far that triggers it. So - I don't understand it either.

> I also want to add that we've only ever seen the issue related to passing a start DateTime with timezone `America/Chicago` while the user's browser local timezone is `America/New_York` and attempting to add `1800000ms` using `Interval.after()`. The date itself does not seem to correlate with any known DST-related dates.

Does this apply to the [two examples you've provided in the other issue](https://github.com/moment/luxon/issues/909#issuecomment-2214924011)? Specifically this one: 

> Error message: Invalid Interval: end before start: The end of an interval must be after its start, but you had start=2024-06-20T13:00:00.000-04:00 and end=2024-06-20T13:30:00.000+09:00

Because `2024-06-20T13:00:00.000-04:00` is _not_ `America/Chicago`! `America/Chicago` is in DST in June, so the offset in June would be `-05:00`. In fact `America/Chicago` _never_ has the offset `-04:00`.

**Comment by icambron** [comment] 2024-09-26 21:36
That's an amazing writeup of how `fixOffset` works, @diesieben07. I'm going to send people to it whenever there are questions about this little chunk of code. I'll reiterate your point that doubts about the code are really only useful if they compared with an example of when it will produce the wrong result.

@esetnik I can appreciate the difficulty in chasing a ghost problem, that is hard to reproduce in isolation. But note that it is _even harder_ for us, because we don't have your code. That's why it's vital that you start pulling out the relevant parts of your code until you have an example that demonstrates the issue. Otherwise we're left to guess, and JS can be a hostile place that seriously complicates that guesswork: different browsers with different bugs, JS apps that have overriden important JS functions, hacks that break Luxon's immutability to directly modify its objects, and so on. That's why Take is pushing so hard for a reproduceable example; it's really the only way we can make progress: "code is X, should do Y, and as you can see it does Z". In other words, we're open to this being a bug, but we need a starting place.

FWIW, I am in `America/New_York` myself, and I see this:

```js
> Interval.after(DateTime.fromISO("2024-05-01T12:00:00.000-05:00", {zone: "America/Chicago"}), 1800000)                                                                                                                                                                                                                                                 
Interval { start: 2024-05-01T12:00:00.000-05:00, end: 2024-05-01T12:30:00.000-05:00 }
```

So let's do this:

1. I'm closing this issue, since I think it's very thoroughly answered.
2. Let's move further discussion of this offset thing back to the original issue
3. Please try to isolate the issue to code we can see and run

**Closed by icambron** 2024-09-26 21:36 UTC
