### ISSUE TITLE
error to line 87

### ISSUE THREAD

**Issue by milone97** [moment/luxon#459] opened 2019-03-04 10:47 UTC
Hi,
I downloaded the file at this link (https://moment.github.io/luxon/global/luxon.js) once imported into the code I get this error at line 87:
_cache.has is not a function
How can I solve?

**Comment by icambron** [comment] 2019-03-04 18:06
Can you give me more information? For example, what browser is this? Can you provide an example I can run?

**Comment by milone97** [comment] 2019-03-05 11:16
Hi,
I use Google Chrome (Version 72.0.3626.119 (Official Build) 64 bit)).
Ex:
File: goalscrorer.jsp
Code:
<script type="text/javascript" src="luxon.js"></script>
<div class="goalscorer-container"></div>

When the browser renders the page, I see that error.

**Comment by icambron** [comment] 2019-03-08 22:04
Looks like you've overriden the `Map` global. I was able to reproduce this issue by doing the same: https://codepen.io/anon/pen/OqgVyZ. You can see the error in the JS console. That first line is the issue.

The code Babel injects into Luxon's build doesn't require that `Map` be defined at all, but it does require that if it's defined, it is the one here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map. Since whatever your `Map` is doesn't have an instance method called `has`, it's breaking.

You'll need to figure out what script is overriding `Map` and fix it (e.g. by assigning to a different global variable). Luxon can't be expected to work if you override browser globals.

**Closed by icambron** 2019-03-08 22:04 UTC
Labels: issue: troubleshooting
