### ISSUE TITLE
Is it constructive to use name-calling in the documentation?

### ISSUE THREAD

**Issue by rigdern** [moment/luxon#1138] opened 2022-02-19 20:11 UTC
The [DST weirdness section of the Time zones and offsets doc](https://github.com/moment/luxon/blob/804bdb8d43f54208fe376468b0ddb6ac2b797891/docs/zones.md#dst-weirdness) refers to our ancestors as "morons":

> Because our ancestors were morons, they opted for a system wherein many governments shift around the local time twice a year for no good reason.

Do we want to keep this usage of the word "morons" in the documentation? It seems to me like name-calling which could set a bad example for [how to have productive discussions on the internet](http://www.paulgraham.com/disagree.html).

## Thoughts on "no good reason" phrasing

I would also think about the part of that sentence that seems to state that there is "no good reason" for DST. Such phrasing could lead to an interpretation that is kind of like indirectly calling our ancestors morons (for example, one might interpret it like this: if there's "no good reason" for DST then whoever invented it must have been a moron!).

If we want to express opinions about DST in the documentation, it could be worthwhile to link to references so readers can form their own opinions about DST. Documents that cover these topics could be enlightening:
- Historical context around the invention of DST and the tradeoffs that lead to its usage.
- Tradeoffs of DST in the modern day.

## Example from elm/time docs

I think the [elm/time documentation](https://package.elm-lang.org/packages/elm/time/1.0.0/) does a good job of conveying the complexities introduced by timezones without including any opinions about whether they were a good idea:

> This is not just UTC-7 or UTC+3 though! Time zones are way more complicated than a simple offset! Every time [Florida switches to DST forever](https://www.npr.org/sections/thetwo-way/2018/03/08/591925587/) or [Samoa switches from UTC-11 to UTC+13](https://en.wikipedia.org/wiki/Time_in_Samoa), some poor soul adds a note to the [IANA time zone database](https://en.wikipedia.org/wiki/IANA_time_zone_database).

**Comment by dobon** [comment] 2022-02-20 00:42
It's a joke. I think that your tone policing is unnecessary and unproductive. The phrasing makes sense, is unambiguous and utterly reasonable as is. Close this issue, in my opinion.

**Comment by dobon** [comment] 2022-02-20 00:49
Levity is not a bug, it is a feature.

**Closed** 2022-02-23 17:10 UTC
