### ISSUE TITLE
toLocaleString presets: Add variant with weekday abv

### ISSUE THREAD

**Issue by networkimprov** [moment/luxon#283] opened 2018-06-25 20:13 UTC
A weekday is usually valuable in a date string. Currently only the HUGE presets show weekday, and none shows an abbreviated weekday. These would be useful:

- Fri October 14, 1983, 1:30 PM EDT
- Fri Oct 14, 1983, 1:30 PM

Were it my call, I would rev DATE*_{MED,FULL}* vs. creating new presets, but either way works :-)

I realize I can make a preset with Object.assign. I raise the above since the existing ones aim to cover common use.

**Comment by icambron** [comment] 2018-06-26 01:28
Yeah, as you can imagine it's pretty hard to get these all exactly right.

I think I'd take `DATETIME_MED_WITH_WEEKDAY` for your second case. The first one would be harder to fit into the scheme.

I'm willing to change the whole scheme for 2.0 were someone to create a clean proposal from the ground up

**Comment by networkimprov** [comment] 2018-06-26 01:54
Seems to me that the FULL presets deserve a weekday abv. They already add one for time zone. (And it's the one I'm specifically interested in.)

For reference, here are Go's presets (scroll to end of section):  
https://golang.org/pkg/time/#pkg-constants

**Comment by gokulsiva** [comment] 2019-07-07 17:00
Can I take this ?
I have to implemet DATETIME_MED_WITH_WEEKDAY only right ?

**Comment by icambron** [comment] 2019-07-07 18:55
Sure. And yes, just that one in isolation. I may redo the presets overall, but that's a separate, more complicated thing.

**Comment by gokulsiva** [comment] 2019-07-08 20:03
@icambron Submitted PR for this issue.
And also while checking these codes I found that outputs for environments with Intl and without Intl differs.
**For example:**
with Intl:
    dt.toLocaleString(DateTime.DATETIME_MED_WITH_SECONDS) // => 6 Aug 2014, 9:15:36
without Intl:
    dt.toLocaleString(DateTime.DATETIME_MED_WITH_SECONDS) // => Aug 6, 2014, 9:15:36 AM


Also AM/PM are added at last by default in environment without Intl.


Is this the intended behaviour ? Am I missing anything ?

**Comment by icambron** [comment] 2019-11-03 17:54
Fixed in #538, so closing this

**Closed by icambron** 2019-11-03 17:54 UTC
Labels: good first contribution, issue: enhancement
