### ISSUE TITLE
`TT` format error

### ISSUE THREAD

**Issue by s97712** [moment/luxon#782] opened 2020-09-21 10:46 UTC
```ts
console.log(luxon.DateTime.fromISO("2020-01-01T00:00:01", {zone: "utc"}).toFormat("HH:mm::ss TT"))
```
It will output `00:00:01 24:00:01`

I think `24:00:01` should be a wrong time.

**Comment by GillesDebunne** [comment] 2020-09-24 19:45
This a duplicate of #726. It is a Chromium issue with ECMA specifications.

**Closed by GillesDebunne** 2020-09-24 19:45 UTC
