### ISSUE TITLE
Midnight showing up different between machines set to UTC

### ISSUE THREAD

**Issue by jesseflorig** [moment/luxon#749] opened 2020-07-30 06:32 UTC
I have the following function:
```
function formatTime(ms) {
  const dateTime = DateTime.fromMillis(ms)
  return dateTime.toLocaleString( DateTime.TIME_24_WITH_SHORT_OFFSET)
}
```
When I pass in `0` I see `00:00:00 UTC` on my local machine.
However, I see `24:00:00 UTC` on my CI server.

I've configured my test suite to force a timezone of UTC, but one represents the midnight hour as `00` and the other as `24`. Is there a way to force one or the other?

**Comment by icambron** [comment] 2020-07-31 16:18
It's almost certainly the locale. Try forcing the locale to the same thing, like `setLocale("en-us")`

**Comment by jesseflorig** [comment] 2020-07-31 17:05
> It's almost certainly the locale. Try forcing the locale to the same thing, like `setLocale("en-us")`

Thank you, that was one of my initial thoughts so I tried:
```
return dateTime.setLocale("en-US").toLocaleString( DateTime.TIME_24_WITH_SHORT_OFFSET)
```
I'm not sure if it's case sensitive but I got the format from running `window.navigator.languages` in Chrome dev console.

Anyhow, that resulted in the same failure.

**Comment by jesseflorig** [comment] 2020-07-31 18:52
For the time being I just moved my test dateTime to 1AM instead of midnight and everything is working as it should. But it would be nice to solve this instead of working around a bug.

**Comment by koitsu** [comment] 2020-07-31 20:29
> It's almost certainly the locale. Try forcing the locale to the same thing, like `setLocale("en-us")`

It isn't the locale. There is a deeper bug with TZ support when it comes to negative TZ offsets. Please see #733 for an example.

**Comment by GillesDebunne** [comment] 2020-08-16 20:27
I'm unable to reproduce this problem. On which browser(s) or node version(s) does it happen?

**Comment by jesseflorig** [comment] 2020-08-17 16:33
> On which browser(s) or node version(s) does it happen?

I've only seen it running Gitlab CI feature and am not sure what their setup is. Since it happens in the test suite, browser version doesn't apply to this bug. I'll try log out the node version Gitlab CI is using, today.

**Comment by GillesDebunne** [comment] 2020-08-17 20:22
I'm closing this bug as a duplicate of #726. Please post your comments there.

**Closed by GillesDebunne** 2020-08-17 20:22 UTC
Labels: issue: troubleshooting
