### ISSUE TITLE
Invalid DateTime in Microsoft Edge

### ISSUE THREAD

**Issue by ewolfe** [moment/luxon#437] opened 2019-02-11 21:37 UTC
I'm seeing an Invalid DateTime in Microsoft Edge with the message `invalidReason: "unsupported zone"` given the following code:

```js
var now = luxon.DateTime.fromISO("2019-02-11T12:53:03.861-08:00", {
  zone: "America/Los_Angeles"
}).toISODate();
window.alert(now);
```

See https://codesandbox.io/s/n0284v72vp for a reproduction

![kapture 2019-02-11 at 13 36 21](https://user-images.githubusercontent.com/32533397/52595202-2493f780-2e02-11e9-87c4-dd9f453e384f.gif)

**Comment by ewolfe** [comment] 2019-02-12 01:56
It seems to fail on:

```js
// https://unpkg.com/luxon@1.11.2/src/zones/IANAZone.js
new Intl.DateTimeFormat("en-US", { timeZone: zone }).format(); // line 60
```
with the exception: `Option value 'AMERICA/LOS_ANGELES' for 'timeZone' is outside of valid range. Expected: ['UTC']`

**Comment by ewolfe** [comment] 2019-02-12 20:57
Well it seems to be a known issue in Edge. Using the polyfill from https://stackoverflow.com/a/54365285 solves the problem. It might be worth adding a note in the documentation somewhere.

**Comment by icambron** [comment] 2019-02-17 17:16
What version of Edge is this? I'd have expected this to work.

**Comment by ewolfe** [comment] 2019-02-17 18:01
"MSEdge on Win10 (x64) Stable (17.17134)" from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by icambron** [comment] 2019-02-27 09:21
I wasn't able to reproduce this, and I have that exact version of Edge; your codesandbox worked just like I'd expect. The workaround you posted is for IE11, and that is documented already. I'm not sure what you could have done to Edge to make it not recognize the zone. I wonder if it's somehow a special build that lacks zone information?

**Comment by icambron** [comment] 2019-05-05 01:09
Closing, since I can't reproduce and the issue has gone silent.

**Closed by icambron** 2019-05-05 01:09 UTC
Labels: issue: troubleshooting
