### ISSUE TITLE
luxon doesn't work on IE11

### ISSUE THREAD

**Issue by c-yan** [moment/luxon#269] opened 2018-06-05 08:01 UTC
I got "Object doesn't support property or method 'find'" on IE 11.

The following is the minimum reproduction code:

```
<!DOCTYPE html>
<html>
<head>
<script type="text/javascript" src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
<script type="text/javascript" src="luxon.min.js"></script>
<script type="text/javascript">
luxon.DateTime.fromFormat('2018/06', 'yyyy/MM').toFormat('yyyy/M');
</script>
</head>
<body></body>
</html>
```

**Comment by c-yan** [comment] 2018-06-06 05:15
I confirmed that it works by referring to [Array.prototype.find()](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/find) and inserting the following code:
```
<script type="text/javascript">
// https://tc39.github.io/ecma262/#sec-array.prototype.find
if (!Array.prototype.find) {
  Object.defineProperty(Array.prototype, 'find', {
    value: function(predicate) {
     // 1. Let O be ? ToObject(this value).
      if (this == null) {
        throw new TypeError('"this" is null or not defined');
      }

      var o = Object(this);

      // 2. Let len be ? ToLength(? Get(O, "length")).
      var len = o.length >>> 0;

      // 3. If IsCallable(predicate) is false, throw a TypeError exception.
      if (typeof predicate !== 'function') {
        throw new TypeError('predicate must be a function');
      }

      // 4. If thisArg was supplied, let T be thisArg; else let T be undefined.
      var thisArg = arguments[1];

      // 5. Let k be 0.
      var k = 0;

      // 6. Repeat, while k < len
      while (k < len) {
        // a. Let Pk be ! ToString(k).
        // b. Let kValue be ? Get(O, Pk).
        // c. Let testResult be ToBoolean(? Call(predicate, T, « kValue, k, O »)).
        // d. If testResult is true, return kValue.
        var kValue = o[k];
        if (predicate.call(thisArg, kValue, k, o)) {
          return kValue;
        }
        // e. Increase k by 1.
        k++;
      }

      // 7. Return undefined.
      return undefined;
    },
    configurable: true,
    writable: true
  });
}
</script>
```

**Comment by c-yan** [comment] 2018-06-06 05:27
It seems not to be used in the range I use, but it seems that findIndex which is also not supported by IE 11 exists in the code as well.
https://github.com/moment/luxon/blob/91e571d7896f1f74e55c8a2fa940100daace94f4/src/impl/conversions.js#L25

**Comment by maggiepint** [comment] 2018-06-06 21:44
Correct - not running in IE was always a constraint of luxon, and is also how this library provides a lot of functionality not available elsewhere. Not sure if @icambron is interested in doing a graceful degredation to IE - I know he has explored it in the past.

**Comment by c-yan** [comment] 2018-06-06 22:00
I think that it is better to improve the situation where we think that luxon will work on IE 10 or later when we read the document.
https://moment.github.io/luxon/docs/manual/matrix.html

**Comment by icambron** [comment] 2018-06-16 17:03
Sorry for the slow response.

Yeah, it's supposed to run with the polyfill, albeit with missing features requiring additional functional polyfills. The problem is that I never test it, so it breaks between releases. I'd take a patch for this.

**Comment by c-yan** [comment] 2018-06-16 22:42
I understand. thanks.

**Comment by idiazroncero** [comment] 2018-09-18 14:55
Just FYI, I just stepped into this issue with a page that needs to support IE11.

It seems that, by default, polyfill.io doesn't include all the polyfills needed. You have to explicitly tell the additional features that need support. You can see the docs on [https://polyfill.io/v2/docs/examples](https://polyfill.io/v2/docs/examples)

In my case, I ended with something like this:

`https://cdn.polyfill.io/v2/polyfill.js?features=default,Array.prototype.filter,String.prototype.repeat,Array.prototype.find,Array.prototype.findIndex`

Maybe this could go into the official docs?

**Comment by stefanmaric** [comment] 2018-10-01 18:05
This can be addressed by including [`@babel/polyfill`](https://babeljs.io/docs/en/babel-polyfill) (`core-js`) in the build process.

**Comment by icambron** [comment] 2018-11-04 04:36
I've updated the Support Matrix and Install doc pages to better reflect the current state of Luxon IE support, and to include @idiazroncero's polyfill specifier.

**Closed by icambron** 2018-11-04 04:36 UTC
Labels: issue: bug, issue: old browser

**Comment by gtempesta** [comment] 2020-09-22 08:07
By using dynamic imports I have managed to use the localization and the timezones that I needed, importing Intl and some modules from date-time-format-timezone. 

Note that I also polyfill all required syntaxes in IE11 using Babel and importing the whole 'core-js' library.

Here is a sample from my app.js file. 
```javascript
// the function which will load every required feature
const loadIntl = async () => {
    await import('intl' /* webpackChunkName: "js/polyfill/intl" */);
    Intl.NumberFormat = IntlPolyfill.NumberFormat;
    Intl.DateTimeFormat = IntlPolyfill.DateTimeFormat;
    await import('intl/locale-data/jsonp/en-US.js' /* webpackChunkName: "js/polyfill/en_US" */);
    await import('date-time-format-timezone/build/browserified/date-time-format-timezone-no-data' /* webpackChunkName: "js/polyfill/date-time-format-timezone" */);
    // only import needed timezones otherwise `date-time-format-timezone` will weight heavier than any other package in your installation
    await import('date-time-format-timezone/build/browserified/data/timezones/tzdata-america-los_angeles' /* webpackChunkName: "js/polyfill/tzdata-america-los_angeles" */);
};
// check if it is IE
const browserIsIE = navigator.userAgent.toUpperCase().indexOf('TRIDENT/') !== -1 || navigator.userAgent.toUpperCase().indexOf('MSIE') !== -1;
// we need the check on IE because window.Intl is present in IE11 but the browser still misses the Localization Tokens and the Timezones
if (browserIsIE || !window.Intl) {
    loadIntl().then(() => {
        console.log('intl polyfills loaded');
    });
}

```
Note that for everything to work correctly you need to wait for every asset to be loaded by the browser: (At the time I'm using jQuery `$(window).on('load', () => {})`).

As stated in the docs, after you have run this you can check if the browser is supporting all required features by printing `Info.features()` like this:

```javascript
import { DateTime, Info } from 'luxon';
$(window).on('load', () => {
  const begginningTimeDate = DateTime.fromObject({
    hour: '9',
    zone: 'America/Los_Angeles',
  }).toLocal();
  console.log(Info.features());
});
```
