### ISSUE TITLE
weekData mutating when accessed

### ISSUE THREAD

**Issue by CSigelmann** [moment/luxon#323] opened 2018-08-27 17:42 UTC
I'm using luxon with vuex and running into a mutability issue. I have a date in the state that I want to access with a getter.
```
currentWeek(state)
{
	return state.currentDay.weekNumber
}
```

This throws a vuex error for mutating the state outside mutation handlers. The problem is that weekData changes from null to not null when I try to access weekNumber. Since luxon objects claim to be immutable this isn't how I expected it to behave.

As a side note, I have an easy work-around by just calling `state.currentDay.plus(0).weekNumber` to create a copy, but avoiding making copies was a big reason for using luxon instead of moment.

**Comment by thewizarodofoz** [comment] 2018-08-28 07:48
I see that this is caused by the internal [cache mechanism](https://github.com/moment/luxon/blob/master/src/datetime.js#L52). that the `weekNumber` getter is using. @icambron can you maybe elaborate on this design?

**Comment by icambron** [comment] 2018-08-29 05:59
There might be some confusion about what we mean by "immutable". It means that the interface is immutable, not that the object doesn't maintain state. Since JS is objects are pretty open to inspection, that means that someone bypassing the interface can see those state changes; i.e. it's difficult to hide the private `weekData` variable from Vuex, which doesn't know what is and isn't part of the interface.

Even Immutable.js objects maintain state. The point of immutability is only that the interface is immutable. In fact that's what *allows* caching. Caching is easy when the properties of the object can't change.

I don't really mind fixing this issue in the sense that if tools like Vuex follow some reasonable convention to delineate private variables, like `_weekData` or somesuch. But I'm not willing to give up caching gains I've perf tested.

**Comment by icambron** [comment] 2018-09-29 19:53
I'm going to close this for age. If there's some way I can modify this library to make tools like Vuex ignore private state, I'd be happy to make them. In the meantime, Luxon has to keep private caches to make perf tolerable.

**Closed by icambron** 2018-09-29 19:53 UTC

**Comment by dm-CaT** [comment] 2020-05-19 17:28
Here is the workaround I used in Angular with NGRX but it could be used anywhere.

```TypeScript
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

import * as lx from 'luxon';
import * as lxt from '../node_modules/luxon/src/impl/conversions.js';


if (environment.production) {
  enableProdMode();
} else {

  // Dirty hack to pass strictStateImmutability check from ngrx (https://ngrx.io/guide/store/configuration/runtime-checks).
  // Remove when the https://github.com/moment/luxon/issues/601 or similiar will be fixed.
  Object.defineProperty(lx.DateTime.prototype, 'weekData', {
    enumerable: false,
    get(this: lx.DateTime) {
      return lxt.gregorianToWeek(this);
    },
    set() { }
  });

}

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.error(err));


```
