### ISSUE TITLE
DateTime.fromFormat fails in some cases when running Node 18.13.0

### ISSUE THREAD

**Issue by jnn-incom** [moment/luxon#1364] opened 2023-01-19 15:43 UTC
**Describe the bug**
I Node 18.13.0 parsing DateTime using the fromFormat method can in some cases fail parsing, where running in previous Node version it would not.

**To Reproduce**

```js
const { DateTime } = require("luxon");

const format = "M/d/yyyy tt";
const dateTimeString = "1/17/2023 11:00:00 PM";

const dateTime = DateTime.fromFormat(dateTimeString, format);

console.log(dateTime.isValid);
// "false" when running in 18.13.0
// "true" when running in 18.12.0

console.log(dateTime.toISO());
// "null" when running in 18.13.0
// "2023-01-17T23:00:00.000+01:00" when running in 18.12.0
```

**Actual vs Expected behavior**
I would expect the outcome of running the snippet to be the same in 18.12.0 and 18.13.0 and that the parsed DateTime is valid.
Instead in 18.12.0 the DateTime is correctly parsed while in 18.13.0 it is invalid.

**Desktop (please complete the following information):**

- OS: Windows 11 (but originally noticed noticed in debian based docker container)
- Browser: Node 18.13.0
- Luxon version: 3.2.1
- Your timezone: Europe/Copenhagen

**Additional context**

**Comment by mohd-akram** [comment] 2023-01-30 16:48
The issue is caused by an update to ICU in Node.js. See nodejs/node#46123. Hopefully this can be fixed on Luxon's side as parsing is currently broken because of it.

**Comment by thatsmydoing** [comment] 2023-02-08 14:03
Note that the ICU is not inherently tied to the nodejs version. That only applies to official builds. If you (or your distribution) builds an older nodejs against the new ICU, the changes noted here still apply (like having non breaking spaces in certain places).

**Comment by Evan-McDonagh** [comment] 2023-02-15 10:59
This issue has cropped up running on Chrome now as well since updating the browser to version 110.

**Comment by pgaspar** [comment] 2023-02-16 22:05
> This issue has cropped up running on Chrome now as well since updating the browser to version 110.

Also seeing this on Chrome 110. Running `fromFormatExplain("12:00 AM", "t")` for example, returns a regex with a weird unicode character instead of a blank space:

```
/^(\d{1,2})(:)(\d{1,2})(\ )(AM|PM)$/i
```

This returns no matches. In Safari, the regex has a normal blank space character and works well.

(We're using v1.28.1)

**Comment by gBusato** [comment] 2023-02-26 14:02
> > This issue has cropped up running on Chrome now as well since updating the browser to version 110.
> 
> Also seeing this on Chrome 110. Running `fromFormatExplain("12:00 AM", "t")` for example, returns a regex with a weird unicode character instead of a blank space:
> 
> ```
> /^(\d{1,2})(:)(\d{1,2})(\ )(AM|PM)$/i
> ```
> 
> This returns no matches. In Safari, the regex has a normal blank space character and works well.
> 
> (We're using v1.28.1)

True, I'm currently experiencing the same issue with node 18.10.0 and Chrome v110

**Closed** 2023-02-28 17:16 UTC
