### ISSUE TITLE
fromObject and toFormat("T") use different timezone when timezone is changed

### ISSUE THREAD

**Issue by anttih** [moment/luxon#603] opened 2019-10-28 08:18 UTC
We are currently relying on the property that

```
DateTime.fromObject({hour: 13, minute: 13}).toFormat("T") === "13:13"
```

is true in all situations (minus locale formatting for the separator). Is this a wrong assumption?

This is in a react-native context, and what happens is that when the app is open and  the user changes the device's timezone and goes back to the app, the condition above doesn't hold. It seems that `fromObject` is using a different zone than what `toFormat("T")` is.

I can also confirm that `Settings.defaultZone` does not get changed when switching timezone in the app, so that value is not in sync with `new Date().getTimezoneOffset()` after the timezone has been changed.

**Comment by icambron** [comment] 2019-10-28 13:26
I'm not really clear on exactly what the scenario is here. Is this it:

```js
DateTime.fromObject({hour: 13, minute: 13}).toFormat("T") //=> "13:13"
var dt = DateTime.fromObject({hour: 13, minute: 13});

// change system zone

dt.toFormat("T") //=> 14:13
```

If that's not the scenario, can you lay out what happens in a similar format?

If that is the scenario, that's expected. Luxon's most important principle is that a DateTime instance represents a specific moment in time. When you change the system zone, the moment in time represented by that Luxon instance doesn't change. It is only now expressed in a different zone.

**Comment by anttih** [comment] 2019-10-28 15:40
The scenario is this:

```
DateTime.fromObject({hour: 13, minute: 13}).toFormat("T") === "13:13"

// change system time zone

// this no longer is true
DateTime.fromObject({hour: 13, minute: 13}).toFormat("T") === "13:13" 
```

In other words, I would expect `fromObject` to be effectful (it relies on the system time zone, obviously) but `toFormat` be a pure function with no side effects (it only depends on the given DateTime). It seems that in our case those two calls are using different time zone settings.

**Comment by icambron** [comment] 2019-10-28 22:36
I was able to reproduce this, at least in Chrome. What happens is that Luxon caches `DateTimeFormat` instances and `DateTimeFormat` instances cache the zone, even when no zone is provided. Here's the equivalent when removing Luxon:

```js
var dtf = new Intl.DateTimeFormat("en", { hour: "numeric", minute: "numeric", hour12: false } );
dtf.format(new Date(2019, 10, 28, 13, 13)) //=> "13:13"

// change my zone

dtf.format(new Date(2019, 10, 28, 13, 13)) //=> "8:13"
```

Seems like the only way to prevent this from happening would be to not cache `DateTimeFormat` instances. However, I did that on purpose because it's a significant performance difference. You can see the commit where my benchmark showed an 85x speedup for `toFormat` when caching these instances: bb77d5e6b968b0a2cc1be72d295f40a43a6687fb.

This is a bug, but I'm not willing to drop 85x speed for fixing it. However, it does look like Chrome in particular may have sped up this operation since I wrote that (just now, I tried some quick benchmarking in v8), so possibly this cache can be removed if similar performance improvements are available in Firefox and Safari. I will do some more testing. In the meantime, you can clear the caches explicitly if you want:

```
Settings.clearCaches()
```

**Comment by icambron** [comment] 2019-10-29 00:52
After some additional testing, I had found that contrary to my hope above, Chrome has not made this faster. Here is the difference between caching DateTimeFormat objects and not caching them:

```
DateTime#toFormat with macro x 221,088 ops/sec ±1.18% (93 runs sampled)
DateTime#toFormat with macro no cache x 1,115 ops/sec ±1.90% (92 runs sampled)
```

So that's a huge speedup that I would lose if I fixed this bug.

There might be more radical solutions, such as incorporating the offset in the cache key. I will think about it, but at this point, the most likely outcome here is `wontfix`

**Comment by anttih** [comment] 2019-10-29 08:54
Thanks for taking a look at this!

For some reason calling `Settings.resetCaches()` does not work either. Might have something to do with how react-native caches modules. And anyhow we would like to not use that hammer approach here.

The reason why luxon is such a great library is that it has a more functional API to dates than moment.js. This behaviour goes against that philosophy and I would personally pay the performance penalty rather than have a stateful API.

A common real world use case for experiencing this bug is with mobile applications. You open the app, go to a plane and cross a timezone. You go back to the app and see that all times are off.

**Comment by anttih** [comment] 2019-10-29 11:38
Is there also a cache for the DateTime's time zone because I get the same time zone after changing it?

```javascript
Date.fromObject({hour: 13, minute: 13}).zoneName === "Europe/Helsinki"

// change timezone

// still true
Date.fromObject({hour: 13, minute: 13}).zoneName === "Europe/Helsinki"
```

**Comment by icambron** [comment] 2019-10-30 06:14
> This behaviour goes against that philosophy and I would personally pay the performance penalty rather than have a stateful API.

It's not a stateful API, just a bug. Almost every immutable library ever uses caching; in fact, one of the nice things about immutability is that you _can_ cache so aggressively, because nothing can change. Statefulness is about the API and its expectations, not the any private state underneath. Here it's just that the private state is managed wrong.

That you would pay a 100x performance penalty to fix that bug makes you an outlier, since I've never even seen this one before. I'm not denying it's a real problem, just saying that the cure is for most users worse than the disease; slowing the library down by two orders of magnitude would bring countless applications to their knees. One of the hard parts of maintaining a widely-used open source library is that you can't please everyone all the time.

But I did think of a better workaround:

```js
DateTime.fromObject({hour: 13, minute: 13, zone: DateTime.local().zoneName });
```

That works by paying the performance penalty on object creation. Since the zone to format in is now explicit, it's part of the cache key and everything works.

You can use that conveniently like this:

```js
DateTime.fromObjectLocal = function(o) {
   var realO = Object.assign({}, o, { zone: DateTime.local().zoneName });
   return DateTime.fromObject(realO);
};
```

(though note that in the upcoming 2.0, it's `fromObject({ hour: 13, minute: 13 }, { zone: ... })`)

Re, your second issue: I can't reproduce that, and I'm confident the code doesn't cache anything there. In fact, my workaround above wouldn't even work if that happened. The implementation of that is [here](https://github.com/moment/luxon/blob/master/src/zones/localZone.js#L27); you can see it's constructing a new Intl.DateTimeFormat object to check what zone it resolves. So you must have something else going on there?

**Closed** 2019-12-10 07:50 UTC
Labels: issue: bug
