### ISSUE TITLE
DateTime.fromISO doesn't work with microsecond precision

### ISSUE THREAD

**Issue by imranismail** [moment/luxon#165] opened 2018-01-25 08:49 UTC
```js
const isoDateTimeStringWithMicrosecondPrecision = '2018-03-26T15:59:59.999999'
const redeemableTo = DateTime.fromISO(response.redeemable_to)

redeemableTo.invalid === 'millisecond out of range'
```

**Comment by imranismail** [comment] 2018-01-25 08:51
Maybe another range condition for microsecond precision here? https://github.com/moment/luxon/blob/a2602aa4a315515a848036ec1c67268602b82a1d/src/impl/conversions.js#L148

Let me know if this is right and I'll send a PR

**Comment by icambron** [comment] 2018-01-26 03:17
I think the problem is upstream of that. Luxon only works in millisecond precision, but it should be able to parse any amount of precision. So by the point that it's checking validity it should have rounded that time up

**Comment by icambron** [comment] 2018-01-27 07:05
Fixed in e3980db. I decided that rather than round up to 16:00:00:00.000, it should round down to 15:59:59:59.999. That has more reasonable semantics and is a whole lot easier than trying to propagate up the rounding. I'll release it shortly in 0.4.0.

**Closed** 2018-01-27 07:06 UTC
Labels: issue: bug

**Comment by imranismail** [comment] 2018-01-29 02:33
@icambron thank you for the prompt fixes!

Has this been released on NPM?

**Comment by icambron** [comment] 2018-01-29 15:04
@imranismail hmm, good catch. It was supposed to be but it has not

**Comment by icambron** [comment] 2018-01-29 15:06
@imranismail ok, released now

**Comment by francisrstokes** [comment] 2018-06-12 13:51
Still seems broken in 1.2.1

```
console.log(new DateTime(getBody.result[0].createdAt))
// > DateTime {
//  ts: 2018-06-12T15:49:16.879+02:00,
//  zone: Europe/Amsterdam,
//  locale: en-US }


console.log(new Date(getBody.result[0].createdAt))
// > 2018-06-12T13:49:16.823Z

console.log(getBody.result[0].createdAt)
// > 2018-06-12T13:49:16.823Z
```
