### ISSUE TITLE
DateTime#isInDST returns false when #offsetName returns offset in DST

### ISSUE THREAD

**Issue by Lx** [moment/luxon#279] opened 2018-06-21 06:57 UTC
In `Australia/Melbourne`, DST finished the second after 2:59:59am on 1 April 2018 and local time went back an hour (i.e. the whole hour of 2am occurred twice, first in AEDT and then in AEST).

A `DateTime` object for 1am local time that day (an hour before DST ends), which occurs once, works as expected:

    const dt_1am = DateTime.fromObject({
      year:   2018,
      month:  4,
      day:    1,
      hour:   1,
      zone:   'Australia/Melbourne',
    });
    > dt_1am.toUTC().toISO()
    < "2018-03-31T14:00:00.000Z" // for reference
    > dt_1am.isInDST
    < true // as expected
    > dt_1am.offsetNameLong
    < "‎ ‎Australian Eastern Daylight Time" // as expected, and in alignment with the isInDST value

A `DateTime` object for 3am local time (the instant after DST ends), which also occurs once, works as expected:

    const dt_3am = DateTime.fromObject({
      year:   2018,
      month:  4,
      day:    1,
      hour:   3,
      zone:   'Australia/Melbourne',
    });
    > dt_3am.toUTC().toISO()
    < "2018-03-31T17:00:00.000Z" // three hours after 1am AEDT, as expected
    > dt_3am.isInDST
    < false // as expected
    > dt_3am.offsetNameLong
    > "‎ ‎Australian Eastern Standard Time" // as expected

Since technically there are two local 2ams for this date, requesting a `DateTime` object for this time should probably fail rather than return one value.  Nonetheless, one value is returned—however, it doesn't clearly represent either of the two 2ams:

    const dt_2am = DateTime.fromObject({
      year:   2018,
      month:  4,
      day:    1,
      hour:   2,
      zone:   'Australia/Melbourne',
    });

    > dt_2am.toUTC().toISO()
    < "2018-03-31T16:00:00.000Z" // one hour before 3am AEST, so this is the “post-DST” 2am
    > dt_2am.isInDST
    < false // as expected for the “post-DST” 2am
    > dt_2am.offsetNameLong
    < "‎ ‎Australian Eastern Daylight Time" // NOT expected for the “post-DST” 2am; should be AEST

In summary:

* Requesting a `DateTime` object for 2am 1 April 2018 `Australia/Melbourne` time doesn't fail, even though it possibly should because it represents two different UTC times an hour apart.
* The non-failure results in an inconsistent `DateTime` object being returned, with the UTC time and `isInDST` values suggesting it represents the “post-DST” time, but the offset name suggesting it represents the “within-DST” time.

At minimum, I'd expect Luxon to return a valid, consistent `DateTime` object for one or the other of the two possible instants (not a hybrid of the two as above).

Ideally, if Luxon offered a way to return all possible `DateTime`s for an ambiguous local time, it could throw an error (or return an invalid time) when asked for a single `DateTime` for an ambiguous local time.  Calling code could catch that error and request multiple results, and then use those multiple results to go back to the user and say, “hey, your entered time of 2am 1 April 2018 is ambiguous—do you mean 2am 1 April 2018 AEDT (UTC+11) or 2am 1 April 2018 AEST (UTC+10)?”

**Comment by Lx** [comment] 2018-06-21 12:42
I'd failed to notice that there's [a rather comprehensive explanation of this very topic](https://moment.github.io/luxon/docs/manual/zones.html#dst-weirdness) in the docs already.  Sorry.  I now see that the default behaviour around ambiguous local times is unlikely to change.

I'm still concerned, though, that the wrong offset name is being applied in one case listed above.  `dt_2am` is for 2am 1 April 2018 AEST (UTC+10), but incorrectly has the offset name of AEDT (which is for UTC+11, even though the offset in the object is UTC+10).

**Comment by icambron** [comment] 2018-06-21 17:19
I suspect that's a bug in your JS runtime. I wasn't able to reproduce it in Chrome or Node 8 (I got standard time for your third code snippet). I'm not sure where you're running this, but can you try this:

```js
new Intl.DateTimeFormat('en', { timeZone: 'Australia/Melbourne', timeZoneName: 'long', hour: 'numeric'}).format(new Date("2018-03-31T16:00:00.000Z"))
```

That code produces `"2 AM Australian Eastern Standard Time"`, for me, but I suspect that it doesn't in your browser. You can also switch 'long' with 'short' to see what it says; in my browser it just uses "GMT+10" as the short version, not "AEST", so I made it spell it out.

**Comment by Lx** [comment] 2018-06-22 04:09
I was using Edge 42.17134.1.0:

    Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)
    Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134

and here's the output:

    > new Intl.DateTimeFormat('en', { timeZone: 'Australia/Melbourne', timeZoneName: 'long', hour: 'numeric' }).format(new Date('2018-03-31T16:00:00.000Z'))
    < "‎2‎ ‎AM‎ ‎Australian Eastern Daylight Time"

so it's definitely not a Luxon issue after all.

**Comment by icambron** [comment] 2018-06-22 07:42
Yup. You should be able to file a bug with Edge over that, however one does that. Unfortunately, not much we can do on this end, so I'm going to close this out.

**Closed by icambron** 2018-06-22 07:42 UTC
Labels: issue: troubleshooting

**Comment by networkimprov** [comment] 2018-07-15 19:38
I suggest you tag issues for bugs caused by the browser so that others can find them, with both a tag for the specific browser and the tag "browser-bug".

Given application of those tags, I'd consider leaving the issues open, since a polyfill fix should be considered if the broswer bug persists.
