### ISSUE TITLE
DateTime.hour is not in a 24-hour format after setting the time zone

### ISSUE THREAD

**Issue by ian-yoder-creditgenie** [moment/luxon#1073] opened 2021-11-05 19:49 UTC
**Describe the bug**
The documentation states that the `hour` property of DateTime is always in a 24-hour format, but that doesn't appear to be true in React Native using Expo. If you use Settings.default or DateTime.setZone() to change the time zone, the `hour` property is returned in a 12-hour format.

**To Reproduce**
console.log('5:00 PM EST hour:', DateTime.fromISO('2021-11-05T17:00:00-04:00').setZone('America/New_York').hour);

**Actual vs Expected behavior**
The code above should log out "5:00 PM EST hour: 17" but instead logs out "5:00 PM EST hour: 5".

**Desktop (please complete the following information):**

- OS: iOS and Android
- Browser: this is happening outside of a browser
- Luxon version: 2.0.2
- Your timezone: America/New_York

**Additional context**
Updated my initial post to make it clear that the issue seems to be specific to mobile devices and/or React Native using Expo.

**Comment by icambron** [comment] 2021-11-06 08:57
Hmm, if I go [here](https://moment.github.io/luxon), open my dev tools, and paste this into my console...

```js
console.log('5:00 PM EST hour:', luxon.DateTime.fromISO('2021-11-05T17:00:00-04:00').setZone('America/New_York').hour);
```

...I get "5:00 PM EST hour: 17".

Can you reproduce this in a JS Fiddle or something?

**Comment by ian-yoder-creditgenie** [comment] 2021-11-07 03:04
Thanks for the response! I just tried it in a JS Fiddle and saw the same result you did (17). That's making me wonder if it's specific to React Native and/or Expo, because that's definitely not what our app is producing.

**Comment by icambron** [comment] 2021-11-07 23:24
Some intermediate info might be helpful. For example:

```js
var base = DateTime.fromISO('2021-11-05T17:00:00-04:00');
console.log(base.offset);
console.log(zoned.hour);

var zoned = base.setZone("America/New_York");
console.log(zoned.offset);
console.log(zoned.toISO());
console.log(zoned.hour);
```

**Comment by danielskowronski** [comment] 2021-11-08 19:17
I have similar issue that happens only on Safari on iPadOS 10.3.3

```
var input="2021-11-08T13:00:00"
var tzid="Europe/Warsaw"

luxon.DateTime.fromISO(input); // returns "2021-11-08T13:00:00.000+01:00"
luxon.DateTime.fromISO(input).setZone(tzid); // returns "2021-11-08T01:00:00.000-11:00"
```

**Comment by icambron** [comment] 2021-11-08 21:08
@danielskowronski can you run this:

```js
var d = new Date("2021-11-08T13:00:00");
new Intl.DateTimeFormat("en", { timeZone: "Europe/Warsaw", hour: "numeric", minute: "numeric", second: "numeric", timeZoneName: "short"}).format(d);
```

(e.g. on, Chrome on Linux that gives me `'7:00:00 PM GMT+1'`)

I ask because Luxon uses a similar call to get the local time in the target zone, and then uses that local time to compute the offset. If that call is going haywire in some particular environment, it could have the effect of seriously confusing Luxon's understanding of the offset.

**Comment by icambron** [comment] 2021-11-08 21:12
Hmm, I wonder if what's happening is that these envs don't support `hourCycle`. That would explain why they're off by 12 hours.

**Comment by icambron** [comment] 2021-11-08 21:41
Ok, I'm now pretty confident this is what's happening. Here's the full backstory:

1. Luxon computes offsets for arbitrary zones by passing the zone and the time into the Intl API and using `formatToParts` to extract the current time. It can then use that time to compute the zone's offset at that time. 
1. For that to work reliably, Luxon always uses 24 hour time so that it knows the "real" hour
1. Before the Intl spec added `hourCycle`, there was another option called `hour12`. You set it if you wanted to override the locale settings and use 24-hour time instead
1. At some point, `hourCycle` was introduced with values like `h11`, `h23`, and `h24` and the spec explained how to map `hour12` to these new values. The gist of the conversion was that `hour12: true` turned into `h24`
2. The semantics of h24 are somewhat insane: it uses 24:00 to mean 00:00 (no change in day). `h23` is what people mean by "24-hour time". This broke Luxon. Here's a discussion: https://bugs.chromium.org/p/chromium/issues/detail?id=1025564&can=2&q=%2224%3A00%22%20datetimeformat
3. For the purposes of computing offsets, this is easy to work around, so Luxon did: it just checks if the hour is 24 and, if so, uses 0 instead
4. However, it also seriously broke Luxon's 24-hour-flavored formatting presets, which supplied `hour12` arguments to Intl. This was harder to fix, because not all browsers supported `hourCycle` yet, so Luxon couldn't use it
5. So for Luxon 2.0, I decided that `hourCycle` was now strong enough, and flipped everything to use `hourCycle: 'h23'`
6. But it's still apparently not supported everywhere, which means that `hourCycle` is ignored and we sometimes interpret PM times as AM times.

So here's the deal:

  * I'm going to revert the switch to `hourCycle` in the offset calculator. That will fix this bug without changing any other behavior. (There are several ways to fix it, including simply changing the locale used, but this one is simplest)
  * I'm _not_ going to revert the use `hourCycle` in the formatting presets like `TIME_24_SIMPLE`. That means that for these older environments, the 24-hour part will continue to be ignored. You can always specify your own using hour12 instead of hourCycle. This is needed because most callers would get incorrect results for midnight.

**Comment by icambron** [comment] 2021-11-08 21:47
Fixed in 1d43d468 and released as 2.1.1. Give it a shot?

**Comment by ian-yoder-creditgenie** [comment] 2021-11-08 21:50
Wow, @icambron, thank you so much for all of the information and the quick turnaround! I will do my best to update the package tonight or early tomorrow and report back.

**Comment by danielskowronski** [comment] 2021-11-09 02:16
> @danielskowronski can you run this:
> 
> ```js
> var d = new Date("2021-11-08T13:00:00");
> new Intl.DateTimeFormat("en", { timeZone: "Europe/Warsaw", hour: "numeric", minute: "numeric", second: "numeric", timeZoneName: "short", hourCycle:"h23"}).format(d);
> ```
> 
> (e.g. on, Chrome on Linux that gives me `'19:00:00 GMT+1'`)
> 
> I ask because Luxon uses a similar call to get the local time in the target zone, and then uses that local time to compute the offset. If that call is going haywire in some particular environment, it could have the effect of seriously confusing Luxon's understanding of the offset.

@icambron on both 2.1.0 and 2.1.1 on that old Safari, it gives me `2:00:00 PM GMT+1`

For a moment, I thought it had issues with DST switchover in that TZ, but the same execution but for `2021-10-08T13:00:00` gives `3:00:00 PM GMT+1` and for `2021-12-08T13:00:00` gives `2:00:00 PM GMT+1`. The switchover date this year was October 30th/31st.

**Comment by danielskowronski** [comment] 2021-11-09 02:30
I think it's due to lack of `hourCycle` support in that Safari version, it was introduced to iOS in Safari 11.0, while I have (and am stuck with) on 10.0 - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat

When I removed `hourCycle` parameter, then desktop Firefox and other browsers started behaving like Safari on iPad

**Comment by ian-yoder-creditgenie** [comment] 2021-11-09 18:28
@icambron I just updated to version 2.1.1 and the hour for 5:00 PM is now showing as 17. Seems like it worked! Thank you so much!

**Closed** 2021-11-09 20:19 UTC
Labels: issue: troubleshooting
